version: '3.7'

services:
  tadam:
    env_file:
      - .env
    build: .
    volumes:
      - ./:/proj
    ports:
      - 8000:8000
    depends_on:
      - db
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: library/postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - wow_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  wow_pg_data: